// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTgcmCupPlOqXBnFlHY0LNJ0yFdu1OXfY',
    appId: '1:21281578455:web:230c0d4efb5d2cd45abf92',
    messagingSenderId: '21281578455',
    projectId: 'flutter-diploma-task',
    authDomain: 'flutter-diploma-task.firebaseapp.com',
    storageBucket: 'flutter-diploma-task.appspot.com',
    measurementId: 'G-HTQF471P52',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMR-RcOwv_QcXEzRiD5T5ES2XqpfAUllM',
    appId: '1:21281578455:android:5c0ebf1d050556635abf92',
    messagingSenderId: '21281578455',
    projectId: 'flutter-diploma-task',
    storageBucket: 'flutter-diploma-task.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAr_jSBkt73jpfBp3uXkru1oP-VtD576GU',
    appId: '1:21281578455:ios:ac72113e188170ea5abf92',
    messagingSenderId: '21281578455',
    projectId: 'flutter-diploma-task',
    storageBucket: 'flutter-diploma-task.appspot.com',
    iosBundleId: 'com.example.routeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAr_jSBkt73jpfBp3uXkru1oP-VtD576GU',
    appId: '1:21281578455:ios:cabc99349ee7faed5abf92',
    messagingSenderId: '21281578455',
    projectId: 'flutter-diploma-task',
    storageBucket: 'flutter-diploma-task.appspot.com',
    iosBundleId: 'com.example.routeApp.RunnerTests',
  );
}
